name: Feature Request
description: Request a new feature.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: summary
    attributes:
      label: Summary of Feature.
      description: Summarize the feature and what it does.
      placeholder: Tell us what you want!
      value: "A cool new feature!"
    validations:
      required: true
