name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    strategy:
      matrix:
        type: [cli, gui]
        target: [debian]
        version: [11, 12]
      fail-fast: false
    name: Build ${{ matrix.type }} for ${{ matrix.target }} using Debian ${{ matrix.version }}
    runs-on: ubuntu-latest
    container: debian:${{ matrix.version }}
    steps:
      - name: Update system
        shell: bash
        run: |
          apt-get update
          apt-get install git sudo -y
      - name: Init tools
        uses: actions/checkout@v4.1.7
        with:
          submodules: true # This line is only needed for building a package, pretty much useless otherwise.
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.11'
      - name: Create Package
        shell: bash
        run: |
          chmod +x *
          ./.$TARGET/setup$TYPE.sh
        env:
          TYPE: ${{ matrix.type }}
          TARGET: ${{ matrix.target }}
      - name: Output the result (debian)
        if: matrix.target == 'debian'
        uses: actions/upload-artifact@v4.3.3
        with:
          name: pbskids-dl_deb_${{ matrix.type }}.deb
          path: /home/runner/work/pbskids-dl/pbskids-dl/pbskids-dl_${{ matrix.type }}_deb.deb
          if-no-files-found: error
      - name: Output the SHA256SUM
        uses: actions/upload-artifact@v4.3.3
        with:
          name: pbskids-dl_${{ matrix.target }}_${{ matrix.type }}.sha256sum
          path: /home/runner/work/pbskids-dl/pbskids-dl/pbskids-dl.sha256sum
          if-no-files-found: warn
      - name: Test Build (debian)
        shell: bash
        run: |
          if [ "$TYPE" = "cli" ]; then
            if [ "$TARGET" = "debian" ]; then
              cd $GITHUB_WORKSPACE
              sudo apt-get install ./pbskids-dl_cli_deb.deb -y
              python3 -m pip install -r requirements.txt
              cd ./.debian
              chmod +x *
              ./filetest.sh ./pbskidsdl_testers.txt
            else
              exit 0
            fi
          else
            exit 0
          fi
        env:
          TYPE: ${{ matrix.type }}
          TARGET: ${{ matrix.target }}
