name: Build packages
run-name: build

on:
  workflow_dispatch:
  push:

jobs:
  build_deb:
    runs-on: ubuntu-latest
    steps:
      - name: Init tools
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tools
        shell: bash
        run: |
         cd $GITHUB_WORKSPACE
         sudo apt install python3-pip
         pip install pyinstaller
         pip install argparse
         pip install urllib3
         pip install beautifulsoup4
         pip install lxml
      - name: Create binary
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          pwd
          chmod +x *
          mkdir pbskids-dl_deb
          cd ./pbskids-dl_deb
          ls -al
          mkdir -p opt/pbskids-dl
          cd ./opt/pbskids-dl
          cp $GITHUB_WORKSPACE/pbskids-dl.py .
          pyinstaller pbskids-dl.py
          ls -al
          chmod +x ./dist/pbskids-dl/pbskids-dl
          cd ../..
          mkdir -p usr/bin
          cd ./usr/bin
          ln -s /opt/pbskids-dl/dist/pbskids-dl/pbskids-dl pbskids-dl
          cp $GITHUB_WORKSPACE/pbskids-dl.sh .
          ls -al
          cd ../../
          mkdir DEBIAN
          cd ./DEBIAN
          cp $GITHUB_WORKSPACE/.debian/control .
          cd $GITHUB_WORKSPACE
          dpkg --build ./pbskids-dl_deb
      - name: Output the result
        uses: actions/upload-artifact@v4
        with:
          name: pbskids-dl.deb
          path: /home/runner/work/pbskids-dl/pbskids-dl/pbskids-dl_deb.deb
      - name: TEST BUILD
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          sudo apt install ./pbskids-dl_deb.deb
          cd ./.debian
          chmod +x *
          ./filetest.sh ./pbskidsdl_testers.txt
          
