name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    strategy:
      matrix:
        type: [cli, gui]
        target: [debian]
      fail-fast: false
    name: Build ${{ matrix.type }} for ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - name: Init tools
        uses: actions/checkout@v4.1.7
        with:
          submodules: true # This line is only needed for building a package, pretty much useless otherwise.
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.11'
      - name: Create Package
        shell: bash
        run: |
          chmod +x *
          ./.$TARGET/setup$TYPE.sh
        env:
          TYPE: ${{ matrix.type }}
          TARGET: ${{ matrix.target }}
      - name: Output the result (debian)
        if: matrix.target == 'debian'
        uses: actions/upload-artifact@v4.3.3
        with:
          name: pbskids-dl_deb_${{ matrix.type }}.deb
          path: /home/runner/work/pbskids-dl/pbskids-dl/pbskids-dl_${{ matrix.type }}_deb.deb
          if-no-files-found: error
      - name: Output the SHA256SUM
        uses: actions/upload-artifact@v4.3.3
        with:
          name: pbskids-dl_${{ matrix.target }}_${{ matrix.type }}.sha256sum
          path: /home/runner/work/pbskids-dl/pbskids-dl/pbskids-dl.sha256sum
          if-no-files-found: warn
      - name: Test Build (debian)
        if: ${{ matrix.target == 'debian' }} && ${{ matrix.type == 'cli' }}
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          sudo apt install ./pbskids-dl_cli_deb.deb
          pip install -r requirements.txt
          cd ./.debian
          chmod +x *
          ./filetest.sh ./pbskidsdl_testers.txt
