# This is a basic workflow to help you get started with Actions

name: Make Packages

run-name: Make Packages


# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:

defaults:
  run:
    working-directory: ./

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a multiple jobs
  build_deb:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Init tools
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tools
        shell: bash
        run: |
         cd $GITHUB_WORKSPACE
         sudo apt install python3-pip
         pip install pyinstaller
      - name: Create binary
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          pyinstaller pbskids-dl.py
          sudo mkdir pbskids-dl
          cd ./pbskids-dl
          sudo mkdir -p opt/pbskids-dl
          cd ./opt/pbskids-dl
          sudo cp $GITHUB_WORKSPACE/pbskids-dl/dist/pbskids-dl/* .
          sudo chmod +x ./pbskids-dl
          cd $GITHUB_WORKSPACE/pbskids_dl
          sudo mkdir -p usr/bin
          cd ./usr/bin
          sudo ln -s /opt/pbskids-dl/pbskids-dl pbskids-dl
          sudo cp $GITHUB_WORKSPACE/pbskids-dl.sh .
          sudo chmod +x ./pbskids-dl*
          cd $GITHUB_WORKSPACE/pbskids-dl
          sudo mkdir DEBIAN
          cd ./DEBIAN
          sudo cp $GITHUB_WORKSPACE/CONTROL .
          cd $GITHUB_WORKSPACE
          sudo dpkg --build ./pbskids-dl
