name: build

on:
  workflow_dispatch:
  push:

jobs:
  build_deb_cli:
    runs-on: ubuntu-latest
    steps:
      - name: Init tools
        uses: actions/checkout@v4.1.6
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.11'
      - name: Install tools
        shell: bash
        run: |
         cd $GITHUB_WORKSPACE
         sudo apt update
         sudo apt install python3-pip -y
         pip install argparse
         pip install urllib3
         pip install beautifulsoup4
         pip install lxml
      - name: Create Package
        shell: bash
        run: |
          chmod +x *
          ./.debian/setupcli.sh
      - name: Output the result
        uses: actions/upload-artifact@v4.3.3
        with:
          name: pbskids-dl.deb
          path: /home/runner/work/pbskids-dl/pbskids-dl/pbskids-dl_deb.deb
      - name: Output the SHA256SUM
        uses: actions/upload-artifact@v4.3.3
        with:
          name: pbskids-dl.sha256sum
          path: /home/runner/work/pbskids-dl/pbskids-dl/pbskids-dl.sha256sum
      - name: Test Build
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          sudo apt install ./pbskids-dl_deb.deb
          cd ./.debian
          chmod +x *
          ./filetest.sh ./pbskidsdl_testers.txt
  build_deb_gui:
    runs-on: ubuntu-latest
    steps:
      - name: Init tools
        uses: actions/checkout@v4.1.6
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.11'
      - name: Create Package
        shell: bash
        run: |
          chmod +x *
          ./.debian/setupgui.sh
      - name: Output the result
        uses: actions/upload-artifact@v4.3.3
        with:
          name: pbskids-dl_gui.deb
          path: /home/runner/work/pbskids-dl/pbskids-dl/pbskids-dl_deb.deb
      - name: Output the SHA256SUM
        uses: actions/upload-artifact@v4.3.3
        with:
          name: pbskids-dl_gui.sha256sum
          path: /home/runner/work/pbskids-dl/pbskids-dl/pbskids-dl.sha256sum
  build_deb_cli_amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Init tools
        uses: actions/checkout@v4.1.6
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.11'
      - name: Install tools
        shell: bash
        run: |
         cd $GITHUB_WORKSPACE
         sudo apt update
         sudo apt install python3-pip -y
         pip install pyinstaller
         pip install argparse
         pip install urllib3
         pip install beautifulsoup4
         pip install lxml
      - name: Create binary
        shell: bash
        run: |
          chmod +x *
          ./.debian/setupcli_amd64.sh
      - name: Output the result
        uses: actions/upload-artifact@v4.3.3
        with:
          name: pbskids-dl_amd64.deb
          path: /home/runner/work/pbskids-dl/pbskids-dl/pbskids-dl_deb.deb
      - name: Output the SHA256SUM
        uses: actions/upload-artifact@v4.3.3
        with:
          name: pbskids-dl_amd64.sha256sum
          path: /home/runner/work/pbskids-dl/pbskids-dl/pbskids-dl.sha256sum
      - name: Test Build
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          sudo apt install ./pbskids-dl_deb.deb
          cd ./.debian
          chmod +x *
          ./filetest.sh ./pbskidsdl_testers.txt
  build_deb_gui_amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Init tools
        uses: actions/checkout@v4.1.6
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.11'
      - name: Install tools
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          sudo apt update
          sudo apt install python3-pip
          pip install pyinstaller
          pip install argparse
          pip install urllib3
          pip install beautifulsoup4
          pip install tk
      - name: Create binary
        shell: bash
        run: |
          chmod +x *
          ./.debian/setupgui_amd64.sh
      - name: Output the result
        uses: actions/upload-artifact@v4.3.3
        with:
          name: pbskids-dl_gui_amd64.deb
          path: /home/runner/work/pbskids-dl/pbskids-dl/pbskids-dl_deb.deb
      - name: Output the SHA256SUM
        uses: actions/upload-artifact@v4.3.3
        with:
          name: pbskids-dl_gui_amd64.sha256sum
          path: /home/runner/work/pbskids-dl/pbskids-dl/pbskids-dl.sha256sum
