name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    strategy:
      matrix:
        target: [debian]
      fail-fast: false
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - name: Init tools
        uses: actions/checkout@v4.1.7
        with:
          submodules: true # This line is only needed for building/testing a package, pretty much useless otherwise.
      - uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.11'
      - name: Create Package
        shell: bash
        run: |
          chmod +x *
          ./.$TARGET/setup.sh
        env:
          TARGET: ${{ matrix.target }}
      - name: Output the result (debian)
        if: matrix.target == 'debian'
        uses: actions/upload-artifact@v4.3.4
        with:
          name: pbskids-dl_debian.deb
          path: pbskids-dl_debian.deb
          if-no-files-found: error
      - name: Output the SHA256SUM
        uses: actions/upload-artifact@v4.3.4
        with:
          name: pbskids-dl_${{ matrix.target }}.sha256sum
          path: pbskids-dl.sha256sum
          if-no-files-found: warn
      - name: Update Nightly Release
        uses: andelf/nightly-release@46e2d5f80828ecc5c2c3c819eb31186a7cf2156c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: 'Nightly Release $$'
          prerelease: true
          body: 'TODO: Add nightly release notes'
          files: |
            ./pbskids-dl_debian.deb
  test:
    strategy:
      matrix:
        target: [debian]
      fail-fast: false
    needs: build
    name: Test for ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - name: Init tools
        uses: actions/checkout@v4.1.7
        with:
          submodules: true # This line is only needed for building/testing a package, pretty much useless otherwise.
      - name: Download the result
        uses: actions/download-artifact@v4.1.8
      - name: Verify SHA256sum (debian)
        if: matrix.target == 'debian'
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          mv ./pbskids-dl_debian.sha256sum ./pbskids-dl_debian.sha256sum.2
          cp ./pbskids-dl_debian.sha256sum.2/pbskids-dl.sha256sum ./pbskids-dl_debian.sha256sum
          mv ./pbskids-dl_debian.deb ./pbskids-dl_debian.deb.2
          cp ./pbskids-dl_debian.deb.2/pbskids-dl_debian.deb ./pbskids-dl_debian.deb
          cat ./pbskids-dl_debian.sha256sum | sha256sum --check
      - name: Install Packages (debian)
        if: matrix.target == 'debian'
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          sudo apt-get update
          sudo apt-get install ./pbskids-dl_debian.deb -y
          python3 -m pip install -r requirements.txt
      - name: Test Build (debian)
        if: matrix.target == 'debian'
        shell: bash
        run: |
          cd ./.debian
          sudo chmod +x ./filetest.sh
          ./filetest.sh ./pbskidsdl_testers.txt
