# This is a basic workflow to help you get started with Actions

name: build

run-name: build


# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:

defaults:
  run:
    working-directory: ./

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a multiple jobs
  build_deb:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Init tools
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tools
        shell: bash
        run: |
         cd $GITHUB_WORKSPACE
         sudo apt install python3-pip
         pip install pyinstaller
         pip install argparse
         pip install urllib3
         pip install beautifulsoup4
      - name: Create binary
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          pwd
          chmod +x *
          mkdir pbskids-dl_deb
          cd ./pbskids-dl_deb
          ls -al
          mkdir -p opt/pbskids-dl
          cd ./opt/pbskids-dl
          cp $GITHUB_WORKSPACE/pbskids-dl.py .
          pyinstaller pbskids-dl.py
          ls -al
          chmod +x ./dist/pbskids-dl/pbskids-dl
          cd ../..
          mkdir -p usr/bin
          cd ./usr/bin
          ln -s /opt/pbskids-dl/dist/pbskids-dl/pbskids-dl pbskids-dl
          cp $GITHUB_WORKSPACE/pbskids-dl.sh .
          ls -al
          cd ../../
          mkdir DEBIAN
          cd ./DEBIAN
          cp $GITHUB_WORKSPACE/CONTROL ./control
          cd $GITHUB_WORKSPACE
          dpkg --build ./pbskids-dl_deb
      - name: Output the result
        uses: actions/upload-artifact@v4
        with:
          name: pbskids-dl.deb
          path: /home/runner/work/pbskids-dl/pbskids-dl/pbskids-dl_deb.deb
